name: build

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"
jobs:
  markscribe:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true

      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          git_committer_name: "Nathanael Esayeas"
          git_committer_email: "nathanael.esayeas@protonmail.com"
          git_push_gpgsign: false # GitHub does not support GPG signed pushes, only signed commits.
          git_config_global: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          commit_message: "Update README.md"
          commit_options: '--amend -S --signoff'
          commit_user_name: "Nathanael Esayeas"
          commit_user_email: "nathanael.esayeas@protonmail.com"
          commit_author: "Nathanael Esayeas <nathanael.esayeas@protonmail.com>"
          push_options: "--force-with-lease"
