name: build

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"
jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.14'

      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true

      - uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_committer_name: "Nathanael Esayeas"
          git_committer_email: "nathanael.esayeas@protonmail.com"
          git_push_gpgsign: false # Github does not support GPG signed pushes, only signed commits.
          git_config_global: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - run: go install github.com/muesli/markscribe@latest

      - run: markscribe -write README.md templates/README.md.tpl
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          commit_message: "Update README.md"
          commit_options: '-S --signoff'
          commit_user_name: "Nathanael Esayeas"
          commit_user_email: "nathanael.esayeas@protonmail.com"
          commit_author: "Nathanael Esayeas <nathanael.esayeas@protonmail.com>"
