name: build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          commit_message: "Update README.md"
          commit_user_name: "Nathanael Esayeas"
          commit_user_email: "nathanael.esayeas@protonmail.com"
          commit_author: "Nathanael Esayeas <nathanael.esayeas@protonmail.com>"
